// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXJ6CQisYtBIytWxqua1YIZ0HnDDGs5U',
    appId: '1:849589899833:web:e5375bef4be6d4821f73e8',
    messagingSenderId: '849589899833',
    projectId: 'loginpage-b7e62',
    authDomain: 'loginpage-b7e62.firebaseapp.com',
    storageBucket: 'loginpage-b7e62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkG_UbOYyxE2xGTGmjrLxKganwvTniYps',
    appId: '1:849589899833:android:abf3d3230719f2a81f73e8',
    messagingSenderId: '849589899833',
    projectId: 'loginpage-b7e62',
    storageBucket: 'loginpage-b7e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YiNrI-CiV8wIw6XhlX-9oD7zZdMBL8Y',
    appId: '1:849589899833:ios:824ceb6cffd67fd21f73e8',
    messagingSenderId: '849589899833',
    projectId: 'loginpage-b7e62',
    storageBucket: 'loginpage-b7e62.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YiNrI-CiV8wIw6XhlX-9oD7zZdMBL8Y',
    appId: '1:849589899833:ios:bf174d9175fcc4361f73e8',
    messagingSenderId: '849589899833',
    projectId: 'loginpage-b7e62',
    storageBucket: 'loginpage-b7e62.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
